name: Deploy cxon schemas

on:
  push:
    branches: [ main ]
    paths:
      - 'schema/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate JSON Schemas
        uses: dsanders11/json-schema-validate-action@v1.4.0
        with:
          schema: schema/cxon.schema.json  
          files: schema/cxon.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./schema
          deploy_branch: gh-pages
